sudo: required
dist: focal
language: generic

services:
  - docker

before_install:
  - docker build -t alexdedmon/react-test -f ./client/Dockerfile.dev ././client

scripts:
  - docker run -e CI=true alexdedmon/react-test npm test

after_success:
  - docker build -t alexdedmon/multi-client ./client
  - docker build -t alexdedmon/multi-nginx ./nginx
  - docker build -t alexdedmon/multi-server ./server 
  - docker build -t alexdedmon/multi-worker ./worker 

  # Log in to the docker CLI
  
  # Take those images and push them to docker hub
