sudo: required
dist: focal
language: generic

services:
  - docker

before_install:
  - docker build -t alexdedmon/react-test -f ./client/Dockerfile.dev ././client

scripts:
  - docker run -e CI=true alexdedmon/react-test npm test

after_success:
  - docker build -t alexdedmon/multi-client ./client
  - docker build -t alexdedmon/multi-nginx ./nginx
  - docker build -t alexdedmon/multi-server ./server 
  - docker build -t alexdedmon/multi-worker ./worker 

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push alexdedmon/multi-client
  - docker push alexdedmon/multi-nginx
  - docker push alexdedmon/multi-server
  - docker push alexdedmon/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-multi"
  env: "Docker-multi-env"
  bucket_name: "elasticbeanstalk-us-east-2-923445559289"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY